import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
    {
        _id: uuid(),
        url: "https://m.media-amazon.com/images/I/81b1PP4RK1L._AC_UY327_FMwebp_QL65_.jpg",
        title: "That Night",
        author: "Nidhi Upadhyay",
        price: "5000",
        discount: "10",
        categoryName: "non-fiction",
    },
    {
        _id: uuid(),
        url: "https://m.media-amazon.com/images/I/51np7YlUSQL._AC_UY327_FMwebp_QL65_.jpg",
        title: "That Night",
        author: "Devashish Sardana",
        price: "3000",
        discount: "10",
        categoryName: "horror",
    },
    {
        _id: uuid(),
        url: "https://m.media-amazon.com/images/I/81b1PP4RK1L._AC_UY327_FMwebp_QL65_.jpg",
        title: "That Night",
        author: "Nidhi Upadhyay",
        price: "5000",
        discount: "10",
        categoryName: "non-fiction",
    },
    {
        _id: uuid(),
        url: "https://m.media-amazon.com/images/I/51np7YlUSQL._AC_UY327_FMwebp_QL65_.jpg",
        title: "That Night",
        author: "Devashish Sardana",
        price: "3000",
        discount: "10",
        categoryName: "horror",
    }, {
        _id: uuid(),
        url: "https://m.media-amazon.com/images/I/81b1PP4RK1L._AC_UY327_FMwebp_QL65_.jpg",
        title: "That Night",
        author: "Nidhi Upadhyay",
        price: "5000",
        discount: "10",
        categoryName: "non-fiction",
    },
    {
        _id: uuid(),
        url: "https://m.media-amazon.com/images/I/51np7YlUSQL._AC_UY327_FMwebp_QL65_.jpg",
        title: "That Night",
        author: "Devashish Sardana",
        price: "3000",
        discount: "10",
        categoryName: "horror",
    }, {
        _id: uuid(),
        url: "https://m.media-amazon.com/images/I/81b1PP4RK1L._AC_UY327_FMwebp_QL65_.jpg",
        title: "That Night",
        author: "Nidhi Upadhyay",
        price: "5000",
        discount: "10",
        categoryName: "non-fiction",
    },
    {
        _id: uuid(),
        url: "https://m.media-amazon.com/images/I/51np7YlUSQL._AC_UY327_FMwebp_QL65_.jpg",
        title: "That Night",
        author: "Devashish Sardana",
        price: "3000",
        discount: "10",
        categoryName: "horror",
    }, {
        _id: uuid(),
        url: "https://m.media-amazon.com/images/I/81b1PP4RK1L._AC_UY327_FMwebp_QL65_.jpg",
        title: "That Night",
        author: "Nidhi Upadhyay",
        price: "5000",
        discount: "10",
        categoryName: "non-fiction",
    },
    {
        _id: uuid(),
        url: "https://m.media-amazon.com/images/I/51np7YlUSQL._AC_UY327_FMwebp_QL65_.jpg",
        title: "That Night",
        author: "Devashish Sardana",
        price: "3000",
        discount: "10",
        categoryName: "horror",
    }, {
        _id: uuid(),
        url: "https://m.media-amazon.com/images/I/81b1PP4RK1L._AC_UY327_FMwebp_QL65_.jpg",
        title: "That Night",
        author: "Nidhi Upadhyay",
        price: "5000",
        discount: "10",
        categoryName: "non-fiction",
    },
    {
        _id: uuid(),
        url: "https://m.media-amazon.com/images/I/51np7YlUSQL._AC_UY327_FMwebp_QL65_.jpg",
        title: "That Night",
        author: "Devashish Sardana",
        price: "3000",
        discount: "10",
        categoryName: "horror",
    },
];
